### ISSUE TITLE
Package name in NPM is not valid (according docs)

### ISSUE THREAD

**Issue by renanwilliam** [woovibr/woovi-nodejs-sdk#48]
[Docs](https://developers.openpix.com.br/docs/sdk/node/sdk-node-usage) mention how to install:

> Run the command below which installs the necessary dependencies with npm:
> 
> `$ npm install @woovi/node-sdk`

But there's no package with this name at [Woovi organization](https://www.npmjs.com/org/woovi)

Is the package unavailable, or is it just a typo?

**Comment by edumaciel10** [comment]
https://www.npmjs.com/package/@woovi/node-sdk

**Comment by renanwilliam** [comment]
Tks
