### ISSUE TITLE
Library did not have been builded before going to production

### ISSUE THREAD

**Issue by eletroswing** [woovibr/woovi-nodejs-sdk#50]
The issue affects the @woovi/node-sdk lib on NPM.

The lib had all its source code delivered to npm along with the docs, but in reality, the npm run build command should be run first, and the contents of dist, and only this should be published.

This error has a simple fix, with serious results, which is a serious issue to be resolved

**Comment by joelbrs** [comment]
if i really understood: the problem is when deliver the code to npm repository. it are not sending just the dist folder but the docs too. 

if so, add a .npmignore file to the project may resolve the issue?

**Comment by eletroswing** [comment]
It may work, the main cause is to run npm run dist to then deliver the code
