### ISSUE TITLE
Cannot find module '@utils/restClient'

### ISSUE THREAD

**Issue by Deepsn** [woovibr/woovi-nodejs-sdk#53]
Recently, I found this package to manage api requests to OpenPix, but when trying to use it, I get an error when creating a client using `createClient`

Code snippet:
```ts
import { createClient } from "@woovi/node-sdk";
import { env } from "./env";

export const openpix = createClient({ appId: env.OPENPIX_APPID });
``` 

Stacktrace:
```
Error: Cannot find module '@utils/restClient'
Require stack:
- \node_modules\.pnpm\@woovi+node-sdk@1.0.1-s\node_modules\@woovi\node-sdk\src\index.ts
```

Using version `1.0.1-s`

Could be related to #50

**Comment by sibelius** [comment]
we need to remove any alias usage from the codebase

**Comment by sibelius** [comment]
can you try in the latest version ?

**Comment by Deepsn** [comment]
Yep, latest version worked out
